spring:
  datasource:
    url: jdbc:h2:mem:test
    username: su
    password:
    driver-class-name: org.h2.Driver

  h2:
    console:
      enabled: true

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true